import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const character = readFileSync(resolve(root, 'assets/mari-character-cutout.webp')).toString('base64')
const favicon = `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="13" fill="#1a0c19"/>
  <circle cx="21" cy="32" r="12" fill="none" stroke="#f35a9c" stroke-width="4"/>
  <circle cx="43" cy="32" r="12" fill="none" stroke="#f35a9c" stroke-width="4"/>
  <path d="M31 30h2M8 28l-5-3M56 28l5-3" stroke="#f35a9c" stroke-width="3" stroke-linecap="round"/>
  <circle cx="21" cy="32" r="3" fill="#c8f13f"/>
  <circle cx="43" cy="32" r="3" fill="#c8f13f"/>
</svg>`

const output = `// Generated by scripts/sync-art.mjs from the optimized project asset.\n` +
  `export const SKIN_ART = 'data:image/webp;base64,${character}'\n` +
  `export const SKIN_FAVICON = \`data:image/svg+xml,\${encodeURIComponent(\`${favicon}\`)}\`\n`

writeFileSync(resolve(root, 'shared/art.js'), output)
console.log('Synced shared/art.js from assets/mari-character-cutout.webp')
